server:
  port: 8083
  servlet:
    context-path: /posts
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/post-service?authSource=admin
      auto-index-creation: true
app:
  services:
    profile:
      url: http://localhost:8081/profile
    file:
      url: http://localhost:8084/file
      